[package]
name = "bovine-inventory-rust"
version = "0.0.1"
authors = ["zahodi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { git = "https://github.com/clap-rs/clap" }
serde = "1.0"
serde_yaml = "0.8"
